const OFFICIAL={
 stations:'https://opendata.mtr.com.hk/data/mtr_lines_and_stations.csv',
 fares:'https://opendata.mtr.com.hk/data/mtr_lines_fares.csv',
 ael:'https://opendata.mtr.com.hk/data/airport_express_fares.csv',
 lrRoutes:'https://opendata.mtr.com.hk/data/light_rail_routes_and_stops.csv',
 lrFares:'https://opendata.mtr.com.hk/data/light_rail_fares.csv',
 busRoutes:'https://opendata.mtr.com.hk/data/mtr_bus_routes.csv',
 busStops:'https://opendata.mtr.com.hk/data/mtr_bus_stops.csv',
 busFares:'https://opendata.mtr.com.hk/data/mtr_bus_fares.csv'
};
const FILES={stations:'data/mtr_lines_and_stations.csv',fares:'data/mtr_lines_fares.csv',ael:'data/airport_express_fares.csv',lrRoutes:'data/light_rail_routes_and_stops.csv',lrFares:'data/light_rail_fares.csv',busRoutes:'data/mtr_bus_routes.csv',busStops:'data/mtr_bus_stops.csv',busFares:'data/mtr_bus_fares.csv'};
const COLORS={ISL:'#0860a8',TWL:'#ed1d24',KTL:'#00a040',TCL:'#f3982d',AEL:'#00888a',DRL:'#e779a8',TML:'#9a3820',EAL:'#62b5e5',TKL:'#7d499d',SIL:'#b5bd00'};
const NAMES={ISL:'港島綫 Island Line',TWL:'荃灣綫 Tsuen Wan Line',KTL:'觀塘綫 Kwun Tong Line',TCL:'東涌綫 Tung Chung Line',AEL:'機場快綫 Airport Express',DRL:'迪士尼綫 Disneyland Resort Line',TML:'屯馬綫 Tuen Ma Line',EAL:'東鐵綫 East Rail Line',TKL:'將軍澳綫 Tseung Kwan O Line',SIL:'南港島綫 South Island Line'};
const STATIC_LINES={
 ISL:['Kennedy Town','HKU','Sai Ying Pun','Sheung Wan','Central','Admiralty','Wan Chai','Causeway Bay','Tin Hau','Fortress Hill','North Point','Quarry Bay','Tai Koo','Sai Wan Ho','Shau Kei Wan','Heng Fa Chuen','Chai Wan'],
 TWL:['Central','Admiralty','Tsim Sha Tsui','Jordan','Yau Ma Tei','Mong Kok','Prince Edward','Sham Shui Po','Cheung Sha Wan','Lai Chi Kok','Mei Foo','Lai King','Kwai Fong','Kwai Hing','Tai Wo Hau','Tsuen Wan'],
 KTL:['Whampoa','Ho Man Tin','Yau Ma Tei','Mong Kok','Prince Edward','Shek Kip Mei','Kowloon Tong','Lok Fu','Wong Tai Sin','Diamond Hill','Choi Hung','Kowloon Bay','Ngau Tau Kok','Kwun Tong','Lam Tin','Yau Tong','Tiu Keng Leng'],
 TCL:['Hong Kong','Kowloon','Olympic','Nam Cheong','Lai King','Tsing Yi','Sunny Bay','Tung Chung'],
 AEL:['Hong Kong','Kowloon','Tsing Yi','Airport','AsiaWorld-Expo'],
 DRL:['Sunny Bay','Disneyland Resort'],
 TML:['Tuen Mun','Siu Hong','Tin Shui Wai','Long Ping','Yuen Long','Kam Sheung Road','Tsuen Wan West','Mei Foo','Nam Cheong','Austin','East Tsim Sha Tsui','Hung Hom','Ho Man Tin','To Kwa Wan','Sung Wong Toi','Kai Tak','Diamond Hill','Hin Keng','Tai Wai','Che Kung Temple','Sha Tin Wai','City One','Shek Mun','Tai Shui Hang','Heng On','Ma On Shan','Wu Kai Sha'],
 EAL:['Admiralty','Exhibition Centre','Hung Hom','Mong Kok East','Kowloon Tong','Tai Wai','Sha Tin','Fo Tan','Racecourse','University','Tai Po Market','Tai Wo','Fanling','Sheung Shui','Lo Wu','Lok Ma Chau'],
 TKL:['North Point','Quarry Bay','Yau Tong','Tiu Keng Leng','Tseung Kwan O','Hang Hau','Po Lam','LOHAS Park'],
 SIL:['Admiralty','Ocean Park','Wong Chuk Hang','Lei Tung','South Horizons']
};
let D={}; let stationMeta=new Map(); let downloaded=0; let mapClickPhase=0;
function parseCSV(text){const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&q&&n==='"'){cell+='"';i++;}else if(c==='"'){q=!q;}else if(c===','&&!q){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(cell);cell='';if(row.some(x=>x!==''))rows.push(row);row=[];}else cell+=c;}if(cell||row.length){row.push(cell);rows.push(row)}if(!rows.length)return[];const h=rows[0].map(x=>x.replace(/^\uFEFF/,'').trim());return rows.slice(1).map(r=>Object.fromEntries(h.map((k,i)=>[k,(r[i]??'').trim()])))}
async function getText(key,force=false){const cache=await caches.open('mtr-fare-data-v2');const local=FILES[key];if(!force){const c=await cache.match(local)||await cache.match(OFFICIAL[key]);if(c){const t=await c.text();return t}}
 let r=await fetch(local,{cache:'no-store'}).catch(()=>null);if(!r||!r.ok||!(await r.clone().text()).trim()){r=await fetch(OFFICIAL[key],{cache:'no-store'});}if(!r.ok)throw new Error(key+' '+r.status);const blob=await r.clone().blob();downloaded+=blob.size;await cache.put(OFFICIAL[key],r.clone());return await r.text()}
async function syncAll(force=false){const st=document.querySelector('#dataStatus');st.textContent='資料：同步中…';downloaded=0;const keys=Object.keys(OFFICIAL);const out=await Promise.allSettled(keys.map(async k=>[k,parseCSV(await getText(k,force))]));out.forEach(x=>{if(x.status==='fulfilled')D[x.value[0]]=x.value[1]});buildMeta();hydrate();localStorage.setItem('mtrLastSync',new Date().toISOString());if(downloaded)localStorage.setItem('mtrLastBytes',String(downloaded));const ok=['stations','fares','ael'].every(k=>D[k]?.length);st.textContent=ok?'資料：官方資料已就緒':'資料：部分資料未能載入';renderStats();return ok}
function buildMeta(){stationMeta.clear();(D.stations||[]).forEach(r=>{const en=r['English Name']||r.STATION_NAME_EN||r.STATION_NAME||r.Station_Name||r.STATION_EN;const zh=r['Chinese Name']||r.STATION_NAME_CH||r.STATION_NAME_TC||'';const id=r['Station ID']||r.STATION_ID||r.STATION_ID_NUM||'';const lc=r['Line Code']||r.LINE_CODE||r.LINE||'';if(en){if(!stationMeta.has(en))stationMeta.set(en,{en,zh,id,lines:new Set});stationMeta.get(en).lines.add(lc)}})}
function labelStation(en){const m=stationMeta.get(en);return m?.zh?`${m.zh} ${en}`:en}
function lineOptions(sel){sel.innerHTML=Object.keys(STATIC_LINES).map(k=>`<option value="${k}">${NAMES[k]}</option>`).join('');paintLine(sel)}
function stationOptions(line,sel,keep){const arr=STATIC_LINES[line]||[];sel.innerHTML=arr.map(s=>`<option value="${s}" ${s===keep?'selected':''}>${labelStation(s)}</option>`).join('')}
function paintLine(sel){sel.style.borderColor=COLORS[sel.value]||'#294767';sel.style.boxShadow=`inset 5px 0 0 ${COLORS[sel.value]||'#294767'}`}
function initPickers(){const fl=$('#fromLine'),tl=$('#toLine');lineOptions(fl);lineOptions(tl);tl.value='TWL';paintLine(tl);stationOptions(fl.value,$('#fromStation'));stationOptions(tl.value,$('#toStation'));fl.onchange=()=>{paintLine(fl);stationOptions(fl.value,$('#fromStation'));markMap()};tl.onchange=()=>{paintLine(tl);stationOptions(tl.value,$('#toStation'));markMap()};$('#fromStation').onchange=markMap;$('#toStation').onchange=markMap}
function renderMap(){const box=$('#networkMap');box.innerHTML=Object.entries(STATIC_LINES).map(([lc,ss])=>`<div class="line-row"><div class="line-label"><i class="line-dot" style="background:${COLORS[lc]}"></i>${NAMES[lc]}</div><div class="station-track" style="--lc:${COLORS[lc]}">${ss.map(s=>`<button class="station-node" data-st="${s}" data-line="${lc}"><i class="node-dot"></i><span>${labelStation(s)}</span></button>`).join('')}</div></div>`).join('');box.querySelectorAll('.station-node').forEach(b=>b.onclick=()=>chooseFromMap(b.dataset.line,b.dataset.st));markMap()}
function chooseFromMap(line,st){if(mapClickPhase===0){setPicker('from',line,st);mapClickPhase=1}else{setPicker('to',line,st);mapClickPhase=0}markMap();window.scrollTo({top:0,behavior:'smooth'})}
function setPicker(which,line,st){const l=$('#'+which+'Line'),s=$('#'+which+'Station');l.value=line;paintLine(l);stationOptions(line,s,st);s.value=st}
function markMap(){const f=$('#fromStation')?.value,t=$('#toStation')?.value;document.querySelectorAll('.station-node').forEach(n=>n.classList.toggle('selected',n.dataset.st===f||n.dataset.st===t))}
function idOf(name){return stationMeta.get(name)?.id||''}
function findFare(rows,from,to){const fid=idOf(from),tid=idOf(to);return rows.find(r=>{const sf=r.SRC_STATION_ID||r.ST_FROM_ID||r.FROM_STATION_ID||r.SOURCE_STATION_ID;const df=r.DEST_STATION_ID||r.ST_TO_ID||r.TO_STATION_ID||r.DESTINATION_STATION_ID;const sn=r.SRC_STATION_NAME||r.ST_FROM||r.FROM_STATION_NAME;const dn=r.DEST_STATION_NAME||r.ST_TO||r.TO_STATION_NAME;return (fid&&tid&&String(sf)===String(fid)&&String(df)===String(tid))||(norm(sn)===norm(from)&&norm(dn)===norm(to))})}
function norm(s){return String(s||'').toLowerCase().replace(/[^a-z0-9]/g,'')}
function fmt(v){const n=Number(v);return Number.isFinite(n)?`HK$${n.toFixed(n%1?1:0)}`:'—'}
function isAELStation(s){return STATIC_LINES.AEL.includes(s)}
function aelFare(from,to,key){const r=findFare(D.ael||[],from,to)||findFare(D.ael||[],to,from);if(!r)return null;let k=key;if(key==='OCT_CON_CHILD_FARE')k='OCT_CHD_FARE';if(key==='SINGLE_ADT_FARE')k='SINGLE_ADT_FARE';if(!r[k]&&key!=='SINGLE_ADT_FARE')k='OCT_ADT_FARE';return {row:r,val:r[k],key:k}}
function calcRail(){const from=$('#fromStation').value,to=$('#toStation').value,key=$('#fareType').value,res=$('#resultCard');if(from===to){show(res,'<b>起點與終點不能相同。</b>');return}
 const a=isAELStation(from),b=isAELStation(to);if(a||b){const direct=a&&b?aelFare(from,to,key):null;if(direct){show(res,`<span class="eyebrow">AIRPORT EXPRESS</span><div class="fare-big">${fmt(direct.val)}</div><div class="route-note">${labelStation(from)} → ${labelStation(to)}</div>${aelRule()}`);return}
 const railStation=a?to:from;const aelEnd=a?from:to;const hubs=['Hong Kong','Kowloon','Tsing Yi'];const opts=hubs.map(h=>({h,x:aelFare(h,aelEnd,key)})).filter(o=>o.x&&Number(o.x.val)>0).sort((x,y)=>Number(x.x.val)-Number(y.x.val));if(opts.length){const best=opts[0];show(res,`<span class="eyebrow">AEL + FREE MTR CONNECTION</span><div class="fare-big">${fmt(best.x.val)}</div><div class="route-note">${labelStation(railStation)} ⇄ <b>${labelStation(best.h)}</b> ⇄ ${labelStation(aelEnd)}<br>顯示最低 AEL 票價的合資格轉乘選項；實際最快路線未必是此站。</div>${aelRule()}<div class="route-note">其他 AEL 上車選項：${opts.map(o=>`${o.h} ${fmt(o.x.val)}`).join(' · ')}</div>`);return}}
 const r=findFare(D.fares||[],from,to);if(!r){show(res,`<b>找不到這一對車站的官方 fare row。</b><div class="route-note">請按「更新官方資料」後再試；若仍無資料，可能是官方 CSV 欄位更新。</div>`);return}let v=r[key];if(v===''||v==null){v=r.OCT_ADT_FARE}show(res,`<span class="eyebrow">MTR FARE</span><div class="fare-big">${fmt(v)}</div><div class="route-note">${labelStation(from)} → ${labelStation(to)}<br>${$('#fareType').selectedOptions[0].text}</div>`)}
function aelRule(){return `<div class="warning">AEL 免費 MTR 接駁須符合港鐵條款：同一合資格付款方式、指定轉乘站及時限；不包括 Light Rail、MTR Bus、東鐵頭等。MTR→AEL 時較低的一程免費。</div>`}
function lrStops(){const set=new Map();(D.lrRoutes||[]).forEach(r=>{const id=r.STOP_ID||r.STATION_ID||r.STOP_CODE||r.LR_STOP_ID;const en=r.STOP_NAME_EN||r.STATION_NAME_EN||r.ENGLISH_NAME||r.STOP_NAME;const zh=r.STOP_NAME_CH||r.STOP_NAME_TC||r.CHINESE_NAME||'';if(id||en)set.set(String(id||en),{id:String(id||''),en:en||String(id),zh})});return [...set.values()]}
function initLR(){const stops=lrStops();['lrFrom','lrTo'].forEach((id,i)=>{$('#'+id).innerHTML=stops.map((s,j)=>`<option value="${s.id||s.en}" ${j===i?'selected':''}>${s.zh?s.zh+' ':''}${s.en}</option>`).join('')});const routes={};(D.lrRoutes||[]).forEach(r=>{const rn=r.ROUTE_ID||r.ROUTE_NO||r.ROUTE||'Light Rail';const name=r.ROUTE_NAME_EN||r.ROUTE_NAME||'';(routes[rn]??=[]).push(name)});$('#lrRoutes').innerHTML=Object.keys(routes).slice(0,20).map(r=>`<div class="mini-line"><strong>Route ${r}</strong><span>點選上方車站即可查價</span></div>`).join('')}
function calcLR(){const f=$('#lrFrom').value,t=$('#lrTo').value,k=$('#lrFareType').value;const rows=D.lrFares||[];const r=rows.find(x=>String(x.SRC_STOP_ID||x.FROM_STOP_ID||x.ST_FROM_ID||x.SRC_STATION_ID)===String(f)&&String(x.DEST_STOP_ID||x.TO_STOP_ID||x.ST_TO_ID||x.DEST_STATION_ID)===String(t));const v=r&&(r[k]||r.OCT_ADT_FARE||r.ADULT_FARE);show($('#lrResult'),r?`<span class="eyebrow lr">LIGHT RAIL FARE</span><div class="fare-big">${fmt(v)}</div><div class="route-note">官方 Light Rail fare matrix</div>`:'<b>找不到這一對輕鐵站的官方 fare row。</b>')}
function initBus(){const routes=[...new Set((D.busRoutes||[]).map(r=>r.ROUTE_ID||r.ROUTE_NO||r.ROUTE).filter(Boolean))].sort();$('#busRoute').innerHTML=routes.map(r=>`<option>${r}</option>`).join('');refreshBusDirection();$('#busRoute').onchange=refreshBusDirection}
function refreshBusDirection(){const r=$('#busRoute').value;const rows=(D.busRoutes||[]).filter(x=>String(x.ROUTE_ID||x.ROUTE_NO||x.ROUTE)===r);$('#busDirection').innerHTML=(rows.length?rows:[{}]).map((x,i)=>`<option value="${i}">${x.DIRECTION||x.BOUND||x.ROUTE_NAME_EN||'Route information'}</option>`).join('')}
function calcBus(){const route=$('#busRoute').value;const fr=(D.busFares||[]).find(x=>String(x.ROUTE_ID||x.ROUTE_NO||x.ROUTE)===route);const fare=fr&&(fr.ADULT_FARE||fr.OCT_ADT_FARE||fr.FARE||fr.FULL_FARE);const stops=(D.busStops||[]).filter(x=>String(x.ROUTE_ID||x.ROUTE_NO||x.ROUTE)===route).sort((a,b)=>Number(a.STOP_SEQ||a.SEQ)-Number(b.STOP_SEQ||b.SEQ));show($('#busResult'),`<span class="eyebrow bus">MTR BUS ${route||''}</span><div class="fare-big">${fare?fmt(fare):'按官方資料'}</div><div class="route-note">${stops.slice(0,40).map(x=>x.STOP_NAME_CH||x.STOP_NAME_TC||x.STOP_NAME_EN||x.STOP_ID).filter(Boolean).join(' → ')||'站點資料未載入'}</div>`)}
function hydrate(){renderMap();initLR();initBus();renderStats()}
function renderStats(){const b=Number(localStorage.getItem('mtrLastBytes')||0),d=localStorage.getItem('mtrLastSync');$('#byteStats').innerHTML=`上次同步：${d?new Date(d).toLocaleString():'尚未完成'}<br>本裝置最近一次新下載：${b?(b/1024).toFixed(1)+' KB':'0 KB / 使用快取'}`}
function show(el,html){el.innerHTML=html;el.classList.remove('hidden')}
function $(q){return document.querySelector(q)}
function tabs(){document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===b.dataset.page));window.scrollTo({top:120,behavior:'smooth'})})}
function boot(){tabs();initPickers();renderMap();$('#calcBtn').onclick=calcRail;$('#lrCalcBtn').onclick=calcLR;$('#busCalcBtn').onclick=calcBus;$('#syncBtn').onclick=()=>syncAll(true);$('#swapBtn').onclick=()=>{const a={l:$('#fromLine').value,s:$('#fromStation').value},b={l:$('#toLine').value,s:$('#toStation').value};setPicker('from',b.l,b.s);setPicker('to',a.l,a.s);markMap()};$('#buildDate').textContent='Build 2026-09-21';if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});syncAll(false).catch(e=>{$('#dataStatus').textContent='資料：未同步（可按更新）';console.error(e)})}
document.addEventListener('DOMContentLoaded',boot);
